[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = [
    "-Lnative=/tmp/xwin/crt/lib/x86_64",
    "-Lnative=/tmp/xwin/sdk/lib/um/x86_64",
    "-Lnative=/tmp/xwin/sdk/lib/ucrt/x86_64"
]

[env]
CC_x86_64_pc_windows_msvc = "clang"
CXX_x86_64_pc_windows_msvc = "clang++"